"""Stable Feed entrypoint for cross-component workflows."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Feed(Protocol):
    def transition_advisory(
        self, *, project_id: str, experiment_id: str, event: str
    ) -> str | None: ...


class FeedDelivery(Protocol):
    """Public single-component API used by HTTP and the local data plane."""

    def register(self, **kwargs: Any) -> dict[str, Any]: ...
    def post(self, **kwargs: Any) -> dict[str, Any]: ...
    def validate_post_intent(self, **kwargs: Any) -> dict[str, Any]: ...
    def post_observed(self, **kwargs: Any) -> dict[str, Any]: ...
    def pending_upload_cap(self, **kwargs: Any) -> int: ...
    def complete_post_upload(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_posts(self, **kwargs: Any) -> dict[str, Any]: ...
    def set_reaction(self, **kwargs: Any) -> dict[str, Any]: ...
    def researcher_reply(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_image(self, **kwargs: Any) -> tuple[bytes, str]: ...
    def get_link_image(self, **kwargs: Any) -> tuple[bytes, str]: ...
    def get_embed(self, **kwargs: Any) -> str: ...


__all__ = ["Feed", "FeedDelivery"]
