"""Pure helpers, constants, and value types for the sandbox stack.

Everything here is free of ``SandboxService`` state — module-level functions,
tunables, the SSH dispatcher template, and pure projection helpers. It lives
outside ``services`` so the data plane can share the same vocabulary without
importing the service package.
"""

from __future__ import annotations

import json
import re
from datetime import datetime
from typing import Any

from ..utils import ValidationError, parse_iso as _parse_iso


VALID_GPUS: frozenset[str] = frozenset(
    {"T4", "L4", "A10G", "L40S", "A100", "A100-80GB", "H100", "B200"}
)
ACTIVE_SANDBOX_STATUSES: frozenset[str] = frozenset({"running"})
MAX_TIME_LIMIT_SECONDS = 24 * 60 * 60
MIN_TIME_LIMIT_SECONDS = 60
DEFAULT_TIME_LIMIT_SECONDS = 3600
DEFAULT_CPU = 2.0
DEFAULT_MEMORY_MB = 8192

# How long sandbox.request waits for a fresh provision to finish before it
# returns `provisioning` and tells the agent to poll. Kept safely under the MCP
# client timeout (~60s) so the call never trips it.
DEFAULT_REQUEST_WAIT_SECONDS = 45.0
# Backstop: a `provisioning` row this old whose job is no longer in this process
# (daemon restart, or a wedged acquire) is reconciled to `failed`.
DEFAULT_STALE_PROVISION_SECONDS = 15 * 60.0
# Billing backstop for a provision that wedged before reaching `running` (daemon
# crash, host reboot, OOM): a `provisioning` row older than this whose job is
# gone has its provider VM reaped, in ANY pre-running phase (the VM exists from
# `creating` onward). Generous enough to clear a slow Lambda cold boot + first
# sync, well under an hour. Drives both the reaper thread (every mode) and the
# control-plane stale-provision sweep, so a wedged provision is bounded, never
# an indefinite billing leak.
DEFAULT_STALE_PROVISION_DEADLINE_SECONDS = 10 * 60.0
# Cadence hint handed to the agent while provisioning. Lambda VMs commonly
# take 5-15 minutes to boot and bootstrap, so a tighter cadence just burns
# calls without learning anything new.
POLL_AFTER_SECONDS = 30
# Live-usage samples are coalesced for this long so the fleet view and the
# drill-in terminal (which both poll ~3s) don't double-exec into a sandbox.
METRICS_CACHE_TTL_SECONDS = 2.0
# Archiving MLflow metrics sweeps the whole REST surface, so dashboard polling
# is throttled to this cadence. Explicit release/reap bypass the throttle.
METRICS_PERSIST_TTL_SECONDS = 60.0
# How often the reaper checks for sandboxes past their expires_at deadline and
# terminates them. Needed because Lambda VMs (unlike Modal sandboxes) have no
# server-side lifetime enforcement, so without this an expired VM bills forever.
DEFAULT_REAPER_INTERVAL_SECONDS = 30.0
DEFAULT_SANDBOX_IDLE_SECONDS = 3600.0

# Static dispatcher dropped at `.research_plugin/sbx`. It resolves the
# sandbox connection file the registry regenerates on every request and
# execs ssh with the boilerplate (-i key, -o flags, user@host) baked in, so the
# agent only ever types `.research_plugin/sbx <experiment_id> '<command>'`.
#
# Reliability behavior (added to survive Modal-tunnel / local-resolver blips —
# the macOS mDNSResponder `-65563` "could not resolve hostname" failure mode):
#   * ControlMaster/ControlPersist multiplex every command for an experiment
#     over ONE connection, so the tunnel hostname is resolved once per session
#     instead of on every call (which is what made a momentary resolver outage
#     break otherwise-healthy sandboxes).
#   * ServerAliveInterval keeps long-running commands from silently dropping.
#   * A connect-phase failure (ssh exit 255 within ConnectTimeout) is retried
#     with exponential backoff + jitter; a 255 *after* the session ran for a
#     while is NOT retried, since the command may have partially executed.
SBX_DISPATCHER = """\
#!/usr/bin/env bash
# research_plugin sandbox SSH dispatcher (generated; do not edit).
# Usage: .research_plugin/sbx <experiment_id> [command...]
# Connection details live in .research_plugin/sandboxes/conn/<experiment_id>
# and are regenerated by sandbox.request / sandbox.get whenever the sandbox is
# (re)created or its tunnel endpoint moves.
set -euo pipefail
here="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
if [[ $# -lt 1 ]]; then
  echo "usage: $(basename "$0") <experiment_id> [command...]" >&2
  exit 2
fi
exp="$1"; shift
conn="$here/sandboxes/conn/$exp"
if [[ ! -f "$conn" ]]; then
  echo "sbx: no active sandbox for '$exp' — call sandbox.request first." >&2
  exit 2
fi
# shellcheck disable=SC1090
source "$conn"

# Per-connection control socket. %C is a short hash of (host,port,user,localhost)
# so the path stays well under the unix-socket length limit even for deep repos.
cmdir="${HOME:-/tmp}/.ssh/rp-cm"
mkdir -p "$cmdir" 2>/dev/null || true

ssh_opts=(
  -i "$RP_SSH_KEY" -p "$RP_SSH_PORT"
  -o BatchMode=yes
  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  -o ConnectTimeout=10
  -o ServerAliveInterval=15 -o ServerAliveCountMax=4
  -o ControlMaster=auto -o "ControlPath=$cmdir/%C" -o ControlPersist=10m
)

attempt=0
max_attempts=5
delay=1
while :; do
  attempt=$((attempt + 1))
  SECONDS=0
  set +e
  ssh "${ssh_opts[@]}" "$RP_SSH_USER@$RP_SSH_HOST" "$@"
  rc=$?
  set -e
  # Non-255 is the remote command's real exit status — return it unchanged.
  if [[ $rc -ne 255 ]]; then
    exit $rc
  fi
  # A 255 after a long session means ssh connected and the command may have
  # run; do not silently re-execute it.
  if [[ $SECONDS -ge 12 ]]; then
    echo "sbx: connection to $RP_SSH_HOST:$RP_SSH_PORT dropped after ${SECONDS}s (rc=255); not retrying (command may have partially run)." >&2
    exit $rc
  fi
  if [[ $attempt -ge $max_attempts ]]; then
    echo "sbx: could not connect to $RP_SSH_HOST:$RP_SSH_PORT after $attempt attempts (rc=255)." >&2
    echo "sbx: sandbox may be alive but its tunnel/DNS is briefly unreachable — retry, or call sandbox.get to refresh the endpoint." >&2
    exit $rc
  fi
  sleep "${delay}.$((RANDOM % 9))"
  delay=$(( delay < 8 ? delay * 2 : 8 ))
done
"""


def _safe_name(experiment_id: str) -> str:
    """Filesystem-safe key/conn filename for an experiment id."""
    return "".join(ch if ch.isalnum() or ch in "-_." else "_" for ch in experiment_id) or "experiment"


def _shq(value: str) -> str:
    """POSIX single-quote a value for safe `source` in the conn file."""
    return "'" + value.replace("'", "'\\''") + "'"


# Markers the in-sandbox rec.sh ForceCommand wrapper writes to the transcript:
#   command start: "[<ts>] $ <command>"
#   command exit:  "[<ts>] (exit <code>)"   (rc captured via PIPESTATUS[0])
# Parsing them lets `terminal` report a structured exit status, so an agent can
# tell when a command finished and whether it succeeded instead of busy-polling
# the transcript tail. Best-effort: a sandbox created before the marker landed,
# an empty log, or a read taken mid-command simply yields None / False.
_EXIT_MARKER_RE = re.compile(r"^\[([^\]]*)\] \(exit (-?\d+)\)[ \t]*$", re.MULTILINE)
_CMD_MARKER_RE = re.compile(r"^\[([^\]]*)\] \$ ", re.MULTILINE)


def parse_terminal_markers(transcript: str) -> tuple[int | None, str | None, bool]:
    """Extract ``(last_exit_code, last_command_finished_at, command_running)``.

    ``command_running`` is True when the most recent command-start marker has no
    following exit marker — i.e. a command is still in flight. A transcript with
    no markers (old sandbox, empty log) degrades to ``(None, None, False)``.
    """
    if not transcript:
        return None, None, False
    last_exit_code: int | None = None
    last_finished_at: str | None = None
    last_exit_end = -1
    exits = list(_EXIT_MARKER_RE.finditer(transcript))
    if exits:
        last = exits[-1]
        last_exit_code = int(last.group(2))
        last_finished_at = last.group(1).strip() or None
        last_exit_end = last.end()
    cmds = list(_CMD_MARKER_RE.finditer(transcript))
    command_running = bool(cmds and cmds[-1].start() > last_exit_end)
    return last_exit_code, last_finished_at, command_running


def validate_request_inputs(
    *,
    gpu: str | None,
    cpu: float | None,
    memory: int | None,
    time_limit: int | None,
    configurable_resources: bool = True,
) -> tuple[str | None, float, int, int]:
    norm_gpu: str | None = None
    if gpu not in (None, ""):
        norm_gpu = str(gpu).upper()
        # On configurable backends (Modal) `gpu` names a concrete attachable GPU,
        # so validate it against the supported set. On bundled-hardware backends
        # (Lambda Labs) `gpu` is only a free-form filter over live instance types
        # — the real selector is `instance_type` — so accept any string here and
        # let capacity resolution reject a genuinely unavailable choice.
        if configurable_resources and norm_gpu not in VALID_GPUS:
            raise ValidationError(
                f"invalid gpu: {gpu}; allowed: {', '.join(sorted(VALID_GPUS))}"
            )
    norm_cpu = float(cpu) if cpu is not None else DEFAULT_CPU
    if norm_cpu <= 0:
        raise ValidationError("cpu must be positive")
    norm_memory = int(memory) if memory is not None else DEFAULT_MEMORY_MB
    if norm_memory < 512:
        raise ValidationError("memory must be at least 512 (MiB)")
    norm_time = int(time_limit) if time_limit is not None else DEFAULT_TIME_LIMIT_SECONDS
    if norm_time < MIN_TIME_LIMIT_SECONDS or norm_time > MAX_TIME_LIMIT_SECONDS:
        raise ValidationError(
            f"time_limit must be between {MIN_TIME_LIMIT_SECONDS} and {MAX_TIME_LIMIT_SECONDS} seconds"
        )
    return norm_gpu, norm_cpu, norm_memory, norm_time


def parse_iso(value: Any) -> datetime | None:
    return _parse_iso(value)


# Dashboards persistence is plain JSON, mirroring how Python sees the field on
# ProvisionedSandbox. Tolerant of legacy/empty values: a missing or unparseable
# column returns {}, never raises. The UI keys on dashboard name (e.g. "mlflow",
# "tensorboard") so adding a new dashboard later only means another key here.
def encode_dashboards(dashboards: Any) -> str:
    if not dashboards:
        return "{}"
    try:
        clean = {
            str(k): str(v)
            for k, v in dict(dashboards).items()
            if isinstance(v, str) and v
        }
    except Exception:  # noqa: BLE001 — never fail the upsert on a malformed map
        return "{}"
    return json.dumps(clean, sort_keys=True)


def decode_dashboards(raw: Any) -> dict[str, str]:
    if not raw:
        return {}
    if isinstance(raw, dict):
        return {str(k): str(v) for k, v in raw.items() if isinstance(v, str) and v}
    try:
        parsed = json.loads(str(raw))
    except (TypeError, ValueError, json.JSONDecodeError):
        return {}
    if not isinstance(parsed, dict):
        return {}
    return {str(k): str(v) for k, v in parsed.items() if isinstance(v, str) and v}
