"""Central sandbox registry.

`SandboxService` is the single authority for sandbox procurement, status, and
shutdown. Policy it owns:

  - **One sandbox per experiment.** The `sandboxes` table is keyed by
    experiment_id; a request upserts that row.
  - **Reuse-if-alive.** A request reuses the experiment's existing sandbox when
    Modal still reports it alive; otherwise it creates a fresh one.
  - **Per-experiment SSH keypair.** The registry generates and owns an ed25519
    keypair per experiment, authorizes the public key in the sandbox, and hands
    the agent a ready-to-run `ssh` command.

The agent never submits commands here. It calls `request` to get SSH details,
then runs commands itself over SSH. Visibility comes from the in-sandbox
transcript, surfaced through `terminal`.
"""

from __future__ import annotations

import os
import subprocess
import threading
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from ..state.activity import ActivityLogger
from ..state.store import StateStore, row_to_dict
from ..utils import NotFoundError, PermissionDeniedError, ValidationError, now_iso
from ..execution import (
    BackendPermissionError,
    BackendUnavailableError,
    BackendValidationError,
    SandboxBackend,
    SandboxRequest,
)


class _Canceled(Exception):
    """Raised inside a provisioning callback to abort acquire on release."""


@dataclass
class _ProvisionJob:
    """A background provisioning thread plus its control signals."""

    thread: threading.Thread
    cancel: threading.Event
    done: threading.Event


VALID_GPUS: frozenset[str] = frozenset(
    {"T4", "L4", "A10G", "L40S", "A100", "A100-80GB", "H100", "B200"}
)
ACTIVE_SANDBOX_STATUSES: frozenset[str] = frozenset({"running"})
MAX_TIME_LIMIT_SECONDS = 24 * 60 * 60
MIN_TIME_LIMIT_SECONDS = 60
DEFAULT_TIME_LIMIT_SECONDS = 3600
DEFAULT_CPU = 2.0
DEFAULT_MEMORY_MB = 8192

# How long sandbox.request waits for a fresh provision to finish before it
# returns `provisioning` and tells the agent to poll. Kept safely under the MCP
# client timeout (~60s) so the call never trips it.
DEFAULT_REQUEST_WAIT_SECONDS = 45.0
# Backstop: a `provisioning` row this old whose job is no longer in this process
# (daemon restart, or a wedged acquire) is reconciled to `failed`.
DEFAULT_STALE_PROVISION_SECONDS = 15 * 60.0
# Cadence hint handed to the agent while provisioning.
POLL_AFTER_SECONDS = 10

# Static dispatcher dropped at `.research_plugin/sbx`. It resolves the
# per-experiment connection file the registry regenerates on every request and
# execs ssh with the boilerplate (-i key, -o flags, user@host) baked in, so the
# agent only ever types `.research_plugin/sbx <experiment_id> '<command>'`.
SBX_DISPATCHER = """\
#!/usr/bin/env bash
# research_plugin sandbox SSH dispatcher (generated; do not edit).
# Usage: .research_plugin/sbx <experiment_id> [command...]
# Connection details live in .research_plugin/sandboxes/conn/<experiment_id>
# and are regenerated by sandbox.request whenever the sandbox is (re)created.
set -euo pipefail
here="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
if [[ $# -lt 1 ]]; then
  echo "usage: $(basename "$0") <experiment_id> [command...]" >&2
  exit 2
fi
exp="$1"; shift
conn="$here/sandboxes/conn/$exp"
if [[ ! -f "$conn" ]]; then
  echo "sbx: no active sandbox for '$exp' — call sandbox.request first." >&2
  exit 2
fi
# shellcheck disable=SC1090
source "$conn"
exec ssh -i "$RP_SSH_KEY" -p "$RP_SSH_PORT" \\
  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
  "$RP_SSH_USER@$RP_SSH_HOST" "$@"
"""


def _safe_name(experiment_id: str) -> str:
    """Filesystem-safe key/conn filename for an experiment id."""
    return "".join(ch if ch.isalnum() or ch in "-_." else "_" for ch in experiment_id) or "experiment"


def _shq(value: str) -> str:
    """POSIX single-quote a value for safe `source` in the conn file."""
    return "'" + value.replace("'", "'\\''") + "'"


class SandboxService:
    """Owns sandbox persistence and delegates provisioning to a backend."""

    def __init__(
        self,
        *,
        store: StateStore,
        sandbox_backend: SandboxBackend,
        activity: ActivityLogger | None = None,
        request_wait_seconds: float | None = None,
        stale_provision_seconds: float | None = None,
    ) -> None:
        self.store = store
        self.backend = sandbox_backend
        self.activity = activity
        self.keys_dir = store.repo_root / ".research_plugin" / "sandboxes" / "keys"
        self.request_wait_seconds = _env_float(
            "RESEARCH_PLUGIN_SANDBOX_REQUEST_WAIT",
            request_wait_seconds,
            DEFAULT_REQUEST_WAIT_SECONDS,
        )
        self.stale_provision_seconds = _env_float(
            "RESEARCH_PLUGIN_SANDBOX_STALE",
            stale_provision_seconds,
            DEFAULT_STALE_PROVISION_SECONDS,
        )
        # In-flight provisioning jobs, keyed by experiment_id.
        self._jobs: dict[str, _ProvisionJob] = {}
        self._jobs_lock = threading.Lock()

    # ---------- agent / tool surface ----------

    def request(
        self,
        *,
        experiment_id: str,
        project_id: str | None = None,
        gpu: str | None = None,
        cpu: float | None = None,
        memory: int | None = None,
        time_limit: int | None = None,
    ) -> dict[str, Any]:
        gpu, cpu, memory, time_limit = _validate_request_inputs(
            gpu=gpu, cpu=cpu, memory=memory, time_limit=time_limit
        )

        # Resolve scope + experiment gate, and read any existing row, in one txn.
        with self.store.transaction() as conn:
            project_id = self.store.require_project_id(conn=conn, project_id=project_id)
            experiment = conn.execute(
                "SELECT * FROM experiments WHERE id = ?", (experiment_id,)
            ).fetchone()
            if experiment is None or experiment["project_id"] != project_id:
                raise NotFoundError(
                    f"experiment not found in project {project_id}: {experiment_id}"
                )
            if experiment["status"] not in {"ready_to_run", "running"}:
                raise PermissionDeniedError(
                    "sandbox.request requires experiment status ready_to_run or running"
                )
            existing = row_to_dict(
                row=conn.execute(
                    "SELECT * FROM sandboxes WHERE experiment_id = ?", (experiment_id,)
                ).fetchone()
            )

        public_key, key_path = self._ensure_keypair(experiment_id=experiment_id)

        # 1) Reuse a live sandbox immediately — the common mid-session case.
        if (
            existing
            and existing.get("status") in ACTIVE_SANDBOX_STATUSES
            and existing.get("sandbox_id")
            and self._is_alive(sandbox_id=str(existing["sandbox_id"]))
        ):
            self._touch_alive(experiment_id=experiment_id)
            self._mark_experiment_running(experiment_id=experiment_id, project_id=project_id)
            row = self._load_row(experiment_id=experiment_id)
            self._emit_event(
                project_id=project_id,
                event_type="sandbox.reused",
                experiment_id=experiment_id,
                payload={"sandbox_id": existing["sandbox_id"]},
            )
            return self._agent_view(row=row, key_path=key_path, reused=True)

        # 2) Otherwise (re)start provisioning in the background and best-effort
        #    wait up to the budget. A big first sync or a cold GPU returns
        #    `provisioning` (the agent polls sandbox.get); a fast one returns SSH
        #    inline, exactly like before. Backend errors are handled inside the
        #    job, which lands the row in `failed` — so request never times out.
        req = SandboxRequest(
            experiment_id=experiment_id,
            project_id=project_id,
            public_key=public_key,
            gpu=gpu,
            cpu=cpu,
            memory=memory,
            time_limit=time_limit,
        )
        job = self._ensure_job(
            experiment_id=experiment_id,
            project_id=project_id,
            req=req,
            existing=existing,
        )
        job.done.wait(timeout=self.request_wait_seconds)
        row = self._load_row(experiment_id=experiment_id)
        reused = False if row.get("status") == "running" else None
        return self._agent_view(row=row, key_path=key_path, reused=reused)

    def get(self, *, experiment_id: str, project_id: str | None = None) -> dict[str, Any]:
        """Read-only poll target. Never provisions; reconciles stale state."""
        try:
            row = self._fetch_scoped(experiment_id=experiment_id, project_id=project_id)
        except NotFoundError:
            # Soften only the genuine "never provisioned" case so the poll loop
            # never has to catch an exception. A project-scope mismatch (the row
            # exists under another project) is a real error and still raises.
            if self._sandbox_exists(experiment_id=experiment_id):
                raise
            return {
                "experiment_id": experiment_id,
                "status": "none",
                "hint": "No sandbox for this experiment — call sandbox.request to create one.",
            }
        row = self._reconcile(row=row)
        key_path = self._key_path(experiment_id=experiment_id)
        return self._agent_view(row=row, key_path=key_path, reused=None)

    def get_for_ui(self, *, experiment_id: str, project_id: str | None = None) -> dict[str, Any]:
        try:
            row = self._fetch_scoped(experiment_id=experiment_id, project_id=project_id)
        except NotFoundError:
            return {"experiment_id": experiment_id, "status": "none", "sandbox": None}
        row = self._reconcile(row=row)
        return self._ui_view(row=row)

    def list_sandboxes(self, *, project_id: str | None = None) -> dict[str, Any]:
        return {"sandboxes": [self._agent_summary(row=row) for row in self._list_rows(project_id=project_id)]}

    def list_for_ui(self, *, project_id: str | None = None) -> dict[str, Any]:
        return {"sandboxes": [self._ui_view(row=row) for row in self._list_rows(project_id=project_id)]}

    def release(self, *, experiment_id: str, project_id: str | None = None) -> dict[str, Any]:
        row = self._fetch_scoped(experiment_id=experiment_id, project_id=project_id)
        # Signal any in-flight provisioning job to abort. It terminates whatever
        # it created via the cancel path (acquire's cleanup), even if create is
        # still mid-flight when we return.
        with self._jobs_lock:
            job = self._jobs.get(experiment_id)
        if job is not None:
            job.cancel.set()
        stopped = False
        if row.get("sandbox_id") and row.get("status") in (ACTIVE_SANDBOX_STATUSES | {"provisioning"}):
            try:
                stopped = self.backend.terminate(sandbox_id=str(row["sandbox_id"]))
            except Exception:  # noqa: BLE001
                stopped = False
        # Belt-and-suspenders: clear any named orphan we may have created.
        self._cleanup_orphan(experiment_id=experiment_id, row=row)
        self._mark_terminated(experiment_id=experiment_id)
        self._emit_event(
            project_id=str(row["project_id"]),
            event_type="sandbox.released",
            experiment_id=experiment_id,
            payload={"sandbox_id": row.get("sandbox_id", ""), "stopped": stopped},
        )
        return self._ui_view(row=self._load_row(experiment_id=experiment_id))

    def terminal(
        self, *, experiment_id: str, project_id: str | None = None, tail: int | None = None
    ) -> dict[str, Any]:
        row = self._fetch_scoped(experiment_id=experiment_id, project_id=project_id)
        transcript = ""
        try:
            transcript = self.backend.read_transcript(
                sandbox_id=str(row.get("sandbox_id") or ""),
                experiment_id=experiment_id,
                volume_name=str(row.get("volume_name") or ""),
                workdir=str(row.get("workdir") or ""),
                tail=tail,
            )
        except Exception as exc:  # noqa: BLE001
            transcript = f"(terminal unavailable: {exc})"
        return {
            "experiment_id": experiment_id,
            "sandbox_id": row.get("sandbox_id", ""),
            "status": row.get("status", "none"),
            "transcript": transcript,
        }

    def health(self) -> dict[str, Any]:
        health = self.backend.health()
        result = {"ok": bool(health.get("ok"))}
        if not result["ok"] and health.get("error"):
            result["error"] = health["error"]
        return result

    def health_for_ui(self) -> dict[str, Any]:
        return self.backend.health()

    # ---------- workflow / home helpers ----------

    def sandboxes_for_experiment(self, *, conn, experiment_id: str) -> list[dict[str, Any]]:
        rows = conn.execute(
            "SELECT * FROM sandboxes WHERE experiment_id = ? ORDER BY rowid DESC",
            (experiment_id,),
        ).fetchall()
        return [self._ui_view(row=row_to_dict(row=row) or {}) for row in rows]

    def sandboxes_for_project(self, *, conn, project_id: str) -> list[dict[str, Any]]:
        rows = conn.execute(
            "SELECT * FROM sandboxes WHERE project_id = ? ORDER BY rowid DESC",
            (project_id,),
        ).fetchall()
        return [self._ui_view(row=row_to_dict(row=row) or {}) for row in rows]

    # ---------- liveness / persistence ----------

    def _reconcile(self, *, row: dict[str, Any]) -> dict[str, Any]:
        """Bring a row in line with reality. Read-only-safe (never provisions).

        - running → confirm liveness; mark terminated if the sandbox is gone.
        - provisioning → if a live job in this process owns it (and it is not
          stale), leave it for the agent to keep polling; otherwise the job is
          gone (daemon restart) or wedged, so clean up any orphan and mark
          failed. This is what guarantees a polling agent always reaches a
          terminal state.
        """
        status = row.get("status")
        exp = str(row.get("experiment_id"))
        if status in ACTIVE_SANDBOX_STATUSES and row.get("sandbox_id"):
            if self._is_alive(sandbox_id=str(row["sandbox_id"])):
                self._touch_alive(experiment_id=exp)
                return self._load_row(experiment_id=exp)
            self._mark_terminated(experiment_id=exp)
            self._emit_event(
                project_id=str(row["project_id"]),
                event_type="sandbox.expired",
                experiment_id=exp,
                payload={"sandbox_id": row.get("sandbox_id", "")},
            )
            return self._load_row(experiment_id=exp)
        if status == "provisioning":
            with self._jobs_lock:
                job = self._jobs.get(exp)
                live_job = bool(job and job.thread.is_alive())
            if live_job and not self._provision_too_old(row=row):
                return row  # genuinely in flight — keep polling
            # The job may have JUST settled; re-read before declaring failure.
            fresh = self._load_row(experiment_id=exp)
            if fresh.get("status") != "provisioning":
                return self._reconcile(row=fresh)
            self._cleanup_orphan(experiment_id=exp, row=fresh)
            self._mark_failed(
                experiment_id=exp,
                error="provisioning interrupted; call sandbox.request again",
            )
            self._emit_event(
                project_id=str(row["project_id"]),
                event_type="sandbox.failed",
                experiment_id=exp,
                payload={"error": "provisioning interrupted"},
            )
            return self._load_row(experiment_id=exp)
        return row

    # ---------- provisioning jobs ----------

    def _ensure_job(
        self,
        *,
        experiment_id: str,
        project_id: str,
        req: SandboxRequest,
        existing: dict[str, Any] | None,
    ) -> _ProvisionJob:
        """Return the in-flight job for this experiment, or start a fresh one.

        Idempotent: a second request during provisioning attaches to the same
        job rather than starting a duplicate.
        """
        with self._jobs_lock:
            job = self._jobs.get(experiment_id)
            if job is not None and job.thread.is_alive():
                return job
        # No live job. Clear any prior/orphan sandbox before a fresh provision so
        # the deterministic Modal name cannot collide (the wedge we hit). Done
        # outside the lock — it may make a network call.
        self._cleanup_orphan(experiment_id=experiment_id, row=existing)
        with self._jobs_lock:
            job = self._jobs.get(experiment_id)
            if job is not None and job.thread.is_alive():
                return job
            self._begin_provisioning_row(
                experiment_id=experiment_id, project_id=project_id, req=req
            )
            cancel = threading.Event()
            done = threading.Event()
            thread = threading.Thread(
                target=self._provision,
                args=(experiment_id, project_id, req, cancel, done),
                name=f"provision-{experiment_id}",
                daemon=True,
            )
            job = _ProvisionJob(thread=thread, cancel=cancel, done=done)
            self._jobs[experiment_id] = job
            thread.start()
            return job

    def _provision(
        self,
        experiment_id: str,
        project_id: str,
        req: SandboxRequest,
        cancel: threading.Event,
        done: threading.Event,
    ) -> None:
        """Background worker: sync → create → tunnel, updating the row per phase."""
        try:
            def on_phase(phase: str, detail: str) -> None:
                if cancel.is_set():
                    raise _Canceled()
                self._set_provision(experiment_id=experiment_id, phase=phase, detail=detail)

            def on_created(sandbox_id: str, sandbox_name: str) -> None:
                # Persist the id the moment it exists so a crash/restart can
                # reconcile or clean it up — this is the orphan fix.
                self._set_provision(
                    experiment_id=experiment_id,
                    sandbox_id=sandbox_id,
                    sandbox_name=sandbox_name,
                )
                if cancel.is_set():
                    raise _Canceled()

            provisioned = self.backend.acquire(
                request=req, on_phase=on_phase, on_created=on_created
            )
            # Release may have arrived during the final, uninterruptible tunnel
            # wait (cancel isn't checked there). Honor it now rather than marking
            # a just-terminated sandbox `running`.
            if cancel.is_set():
                try:
                    self.backend.terminate(sandbox_id=provisioned.sandbox_id)
                except Exception:  # noqa: BLE001
                    pass
                self._mark_terminated(experiment_id=experiment_id)
                self._emit_event(
                    project_id=project_id,
                    event_type="sandbox.released",
                    experiment_id=experiment_id,
                    payload={"canceled": True},
                )
                return
            now = now_iso()
            self._upsert_sandbox(
                experiment_id=experiment_id,
                project_id=project_id,
                status="running",
                sandbox_id=provisioned.sandbox_id,
                ssh_host=provisioned.ssh_host,
                ssh_port=provisioned.ssh_port,
                ssh_user=provisioned.ssh_user,
                workdir=provisioned.workdir,
                volume_name=provisioned.volume_name,
                expires_at=_iso_after(seconds=req.time_limit),
                last_seen_at=now,
                phase="",
                detail="",
                error="",
                terminated_at="",
            )
            self._mark_experiment_running(experiment_id=experiment_id, project_id=project_id)
            self._emit_event(
                project_id=project_id,
                event_type="sandbox.created",
                experiment_id=experiment_id,
                payload={
                    "sandbox_id": provisioned.sandbox_id,
                    "gpu": req.gpu or "",
                    "time_limit": req.time_limit,
                },
            )
        except _Canceled:
            # acquire already terminated anything it created.
            self._mark_terminated(experiment_id=experiment_id)
            self._emit_event(
                project_id=project_id,
                event_type="sandbox.released",
                experiment_id=experiment_id,
                payload={"canceled": True},
            )
        except (BackendUnavailableError, BackendValidationError, BackendPermissionError) as exc:
            self._mark_failed(experiment_id=experiment_id, error=str(exc))
            self._emit_event(
                project_id=project_id,
                event_type="sandbox.failed",
                experiment_id=experiment_id,
                payload={"error": str(exc)},
            )
        except Exception as exc:  # noqa: BLE001 — never lose the row to an unexpected error
            self._mark_failed(experiment_id=experiment_id, error=str(exc))
            self._emit_event(
                project_id=project_id,
                event_type="sandbox.failed",
                experiment_id=experiment_id,
                payload={"error": str(exc)},
            )
        finally:
            done.set()
            with self._jobs_lock:
                current = self._jobs.get(experiment_id)
                if current is not None and current.done is done:
                    self._jobs.pop(experiment_id, None)

    def _begin_provisioning_row(
        self, *, experiment_id: str, project_id: str, req: SandboxRequest
    ) -> None:
        now = now_iso()
        self._upsert_sandbox(
            experiment_id=experiment_id,
            project_id=project_id,
            status="provisioning",
            phase="starting",
            detail="",
            error="",
            sandbox_id="",
            sandbox_name="",
            ssh_host="",
            ssh_port=0,
            ssh_user="root",
            gpu=req.gpu or "",
            cpu=req.cpu,
            memory=req.memory,
            time_limit=req.time_limit,
            key_path=str(self._key_path(experiment_id=experiment_id)),
            requested_at=now,
            provision_started_at=now,
            expires_at="",
            last_seen_at=now,
            terminated_at="",
        )

    def _set_provision(
        self,
        *,
        experiment_id: str,
        phase: str | None = None,
        detail: str | None = None,
        sandbox_id: str | None = None,
        sandbox_name: str | None = None,
    ) -> None:
        fields: dict[str, Any] = {"status": "provisioning"}
        if phase is not None:
            fields["phase"] = phase
        if detail is not None:
            fields["detail"] = detail
        if sandbox_id is not None:
            fields["sandbox_id"] = sandbox_id
        if sandbox_name is not None:
            fields["sandbox_name"] = sandbox_name
        self._upsert_sandbox(experiment_id=experiment_id, **fields)

    def _cleanup_orphan(self, *, experiment_id: str, row: dict[str, Any] | None) -> None:
        """Best-effort terminate any sandbox tied to this experiment.

        Covers both a recorded sandbox_id (from a prior/failed row) and the
        deterministic-named orphan a dead job may have left on the backend.
        """
        seen: set[str] = set()
        sid = (row or {}).get("sandbox_id")
        if sid:
            seen.add(str(sid))
            try:
                self.backend.terminate(sandbox_id=str(sid))
            except Exception:  # noqa: BLE001
                pass
        finder = getattr(self.backend, "find_sandbox_id", None)
        if callable(finder):
            try:
                orphan = finder(experiment_id=experiment_id)
            except Exception:  # noqa: BLE001
                orphan = None
            if orphan and str(orphan) not in seen:
                try:
                    self.backend.terminate(sandbox_id=str(orphan))
                except Exception:  # noqa: BLE001
                    pass

    def _mark_failed(self, *, experiment_id: str, error: str) -> None:
        now = now_iso()
        with self.store.transaction() as conn:
            conn.execute(
                """
                UPDATE sandboxes
                SET status = 'failed', error = ?, phase = '', detail = '',
                    terminated_at = ?, updated_at = ?
                WHERE experiment_id = ?
                """,
                (error, now, now, experiment_id),
            )
        self._remove_conn(experiment_id=experiment_id)

    def _provision_too_old(self, *, row: dict[str, Any]) -> bool:
        started = _parse_iso(row.get("provision_started_at"))
        if started is None:
            return False
        return (datetime.now(tz=UTC) - started).total_seconds() > self.stale_provision_seconds

    def shutdown(self) -> None:
        """Signal all in-flight provisioning jobs to stop (best-effort)."""
        with self._jobs_lock:
            jobs = list(self._jobs.values())
        for job in jobs:
            job.cancel.set()

    def _is_alive(self, *, sandbox_id: str) -> bool:
        try:
            return bool(self.backend.is_alive(sandbox_id=sandbox_id))
        except Exception:  # noqa: BLE001
            return False

    def _upsert_sandbox(self, *, experiment_id: str, **fields: Any) -> None:
        now = now_iso()
        with self.store.transaction() as conn:
            exists = conn.execute(
                "SELECT 1 FROM sandboxes WHERE experiment_id = ?", (experiment_id,)
            ).fetchone()
            payload = dict(fields)
            payload["updated_at"] = now
            if exists is None:
                payload["experiment_id"] = experiment_id
                payload.setdefault("created_at", now)
                columns = ", ".join(payload)
                placeholders = ", ".join("?" for _ in payload)
                conn.execute(
                    f"INSERT INTO sandboxes ({columns}) VALUES ({placeholders})",
                    list(payload.values()),
                )
            else:
                assignments = ", ".join(f"{key} = ?" for key in payload)
                conn.execute(
                    f"UPDATE sandboxes SET {assignments} WHERE experiment_id = ?",
                    [*payload.values(), experiment_id],
                )

    def _touch_alive(self, *, experiment_id: str) -> None:
        now = now_iso()
        with self.store.transaction() as conn:
            conn.execute(
                "UPDATE sandboxes SET last_seen_at = ?, updated_at = ? WHERE experiment_id = ?",
                (now, now, experiment_id),
            )

    def _mark_terminated(self, *, experiment_id: str) -> None:
        now = now_iso()
        with self.store.transaction() as conn:
            conn.execute(
                """
                UPDATE sandboxes
                SET status = 'terminated', terminated_at = ?, updated_at = ?
                WHERE experiment_id = ?
                """,
                (now, now, experiment_id),
            )
        self._remove_conn(experiment_id=experiment_id)

    def _mark_experiment_running(self, *, experiment_id: str, project_id: str) -> None:
        with self.store.transaction() as conn:
            row = conn.execute(
                "SELECT status FROM experiments WHERE id = ?", (experiment_id,)
            ).fetchone()
            if row is None or row["status"] != "ready_to_run":
                return
            conn.execute(
                "UPDATE experiments SET status = 'running', updated_at = ? WHERE id = ?",
                (now_iso(), experiment_id),
            )

    def _load_row(self, *, experiment_id: str) -> dict[str, Any]:
        conn = self.store.connect()
        try:
            row = conn.execute(
                "SELECT * FROM sandboxes WHERE experiment_id = ?", (experiment_id,)
            ).fetchone()
            if row is None:
                raise NotFoundError(f"sandbox not found: {experiment_id}")
            return row_to_dict(row=row) or {}
        finally:
            conn.close()

    def _fetch_scoped(self, *, experiment_id: str, project_id: str | None) -> dict[str, Any]:
        conn = self.store.connect()
        try:
            if project_id is not None:
                project_id = self.store.require_project_id(conn=conn, project_id=project_id)
            row = conn.execute(
                "SELECT * FROM sandboxes WHERE experiment_id = ?", (experiment_id,)
            ).fetchone()
            if row is None:
                raise NotFoundError(f"no sandbox for experiment: {experiment_id}")
            if project_id is not None and row["project_id"] != project_id:
                raise NotFoundError(
                    f"sandbox not found in project {project_id}: {experiment_id}"
                )
            return row_to_dict(row=row) or {}
        finally:
            conn.close()

    def _sandbox_exists(self, *, experiment_id: str) -> bool:
        conn = self.store.connect()
        try:
            return (
                conn.execute(
                    "SELECT 1 FROM sandboxes WHERE experiment_id = ?", (experiment_id,)
                ).fetchone()
                is not None
            )
        finally:
            conn.close()

    def _list_rows(self, *, project_id: str | None) -> list[dict[str, Any]]:
        conn = self.store.connect()
        try:
            project_id = self.store.require_project_id(conn=conn, project_id=project_id)
            rows = conn.execute(
                "SELECT * FROM sandboxes WHERE project_id = ? ORDER BY rowid DESC",
                (project_id,),
            ).fetchall()
            return [row_to_dict(row=row) or {} for row in rows]
        finally:
            conn.close()

    def _emit_event(
        self, *, project_id: str, event_type: str, experiment_id: str, payload: dict[str, Any]
    ) -> None:
        with self.store.transaction() as conn:
            self.store.record_event(
                conn=conn,
                project_id=project_id,
                event_type=event_type,
                target_type="sandbox",
                target_id=experiment_id,
                payload=payload,
            )

    # ---------- keypair ----------

    def _key_path(self, *, experiment_id: str) -> Path:
        return self.keys_dir / _safe_name(experiment_id)

    def _ensure_keypair(self, *, experiment_id: str) -> tuple[str, Path]:
        key_path = self._key_path(experiment_id=experiment_id)
        pub_path = key_path.with_suffix(".pub")
        if key_path.exists() and pub_path.exists():
            return pub_path.read_text().strip(), key_path
        self.keys_dir.mkdir(parents=True, exist_ok=True)
        # Remove a half-written pair before regenerating.
        for path in (key_path, pub_path):
            if path.exists():
                path.unlink()
        try:
            subprocess.run(
                [
                    "ssh-keygen", "-t", "ed25519", "-N", "", "-q",
                    "-C", f"research-plugin-{experiment_id}",
                    "-f", str(key_path),
                ],
                check=True,
                capture_output=True,
                text=True,
            )
        except FileNotFoundError as exc:
            raise ValidationError(
                "ssh-keygen is required to provision sandbox SSH access but was not found"
            ) from exc
        except subprocess.CalledProcessError as exc:
            raise ValidationError(
                f"failed to generate sandbox SSH key: {exc.stderr or exc.stdout or exc}"
            ) from exc
        try:
            os.chmod(key_path, 0o600)
        except OSError:
            pass
        return pub_path.read_text().strip(), key_path

    # ---------- views ----------

    def _raw_ssh_command(self, *, row: dict[str, Any], key_path: Path) -> str:
        host = row.get("ssh_host") or ""
        port = row.get("ssh_port") or 0
        user = row.get("ssh_user") or "root"
        return (
            f"ssh -i {key_path} -p {port} "
            "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
            f"{user}@{host}"
        )

    def _command_paths(self) -> tuple[Path, Path]:
        research_dir = self.store.repo_root / ".research_plugin"
        return research_dir / "sbx", research_dir / "sandboxes" / "conn"

    def _ensure_dispatcher(self, *, dispatcher: Path) -> None:
        """Write the static `sbx` dispatcher once (idempotent)."""
        try:
            if dispatcher.exists() and dispatcher.read_text() == SBX_DISPATCHER:
                return
            dispatcher.parent.mkdir(parents=True, exist_ok=True)
            dispatcher.write_text(SBX_DISPATCHER)
            os.chmod(dispatcher, 0o755)
        except OSError:
            # The dispatcher is a convenience; never fail provisioning over it.
            # The raw_command fallback still works.
            pass

    def _write_command_wrapper(self, *, row: dict[str, Any], key_path: Path) -> str:
        """Refresh the per-experiment conn file and return the short command.

        Returns `.research_plugin/sbx <experiment_id>` (relative to the repo
        root). Returns "" if the wrapper could not be written, so the caller
        falls back to the raw ssh line.
        """
        dispatcher, conn_dir = self._command_paths()
        safe = _safe_name(str(row.get("experiment_id") or ""))
        try:
            self._ensure_dispatcher(dispatcher=dispatcher)
            conn_dir.mkdir(parents=True, exist_ok=True)
            conn_file = conn_dir / safe
            conn_file.write_text(
                f"RP_SSH_KEY={_shq(str(key_path))}\n"
                f"RP_SSH_HOST={_shq(str(row.get('ssh_host') or ''))}\n"
                f"RP_SSH_PORT={_shq(str(row.get('ssh_port') or ''))}\n"
                f"RP_SSH_USER={_shq(str(row.get('ssh_user') or 'root'))}\n"
            )
            os.chmod(conn_file, 0o600)
        except OSError:
            return ""
        rel = os.path.relpath(dispatcher, self.store.repo_root)
        return f"{rel} {safe}"

    def _remove_conn(self, *, experiment_id: str) -> None:
        """Drop the conn file so `sbx` fails loudly for a dead sandbox."""
        _, conn_dir = self._command_paths()
        try:
            (conn_dir / _safe_name(experiment_id)).unlink(missing_ok=True)
        except OSError:
            pass

    def _agent_view(
        self, *, row: dict[str, Any], key_path: Path, reused: bool | None
    ) -> dict[str, Any]:
        status = row.get("status") or "none"
        live = bool(
            row.get("ssh_host")
            and row.get("ssh_port")
            and status in ACTIVE_SANDBOX_STATUSES
        )
        command = self._write_command_wrapper(row=row, key_path=key_path) if live else ""
        raw_command = self._raw_ssh_command(row=row, key_path=key_path) if live else ""
        view: dict[str, Any] = {
            "experiment_id": row.get("experiment_id"),
            "project_id": row.get("project_id"),
            "sandbox_id": row.get("sandbox_id"),
            "status": status,
            "ssh": {
                "host": row.get("ssh_host"),
                "port": row.get("ssh_port"),
                "user": row.get("ssh_user"),
                "key_path": str(key_path),
                "command": command,
                "raw_command": raw_command,
            },
            "workdir": row.get("workdir"),
            "volume": row.get("volume_name"),
            "gpu": row.get("gpu") or None,
            "cpu": row.get("cpu"),
            "memory": row.get("memory"),
            "expires_at": row.get("expires_at"),
        }
        if status == "provisioning":
            view["phase"] = row.get("phase") or "starting"
            view["detail"] = row.get("detail") or ""
            view["poll_after_seconds"] = POLL_AFTER_SECONDS
            view["hint"] = (
                "Provisioning (a large first sync or cold start can take a few "
                "minutes). Poll sandbox.get every ~10s until status is running, "
                "then run commands with ssh.command. Do not re-call "
                "sandbox.request to poll."
            )
        elif status == "failed":
            view["error"] = row.get("error") or "provisioning failed"
            view["hint"] = (
                "Provisioning failed (see error). Fix the cause if you can, then "
                "call sandbox.request to retry."
            )
        elif live:
            view["hint"] = (
                f"Run commands with: {command} '<your shell command>' (from the repo root). "
                "Output streams back and is recorded to the experiment terminal. "
                "Use ssh.raw_command instead if you are not in the repo root. "
                "The repo is mounted at the workdir on a shared Modal Volume."
            )
        else:
            view["hint"] = "No live sandbox for this experiment — call sandbox.request to create one."
        if reused is not None:
            view["reused"] = reused
        return view

    def _agent_summary(self, *, row: dict[str, Any]) -> dict[str, Any]:
        return {
            "experiment_id": row.get("experiment_id"),
            "sandbox_id": row.get("sandbox_id"),
            "status": row.get("status"),
            "gpu": row.get("gpu") or None,
            "expires_at": row.get("expires_at"),
        }

    def _ui_view(self, *, row: dict[str, Any]) -> dict[str, Any]:
        return {
            "experiment_id": row.get("experiment_id"),
            "project_id": row.get("project_id"),
            "sandbox_id": row.get("sandbox_id"),
            "status": row.get("status"),
            "phase": row.get("phase") or "",
            "detail": row.get("detail") or "",
            "error": row.get("error") or "",
            "gpu": row.get("gpu") or "",
            "cpu": row.get("cpu"),
            "memory": row.get("memory"),
            "time_limit": row.get("time_limit"),
            "ssh_host": row.get("ssh_host"),
            "ssh_port": row.get("ssh_port"),
            "ssh_user": row.get("ssh_user"),
            "workdir": row.get("workdir"),
            "volume_name": row.get("volume_name"),
            "requested_at": row.get("requested_at"),
            "expires_at": row.get("expires_at"),
            "last_seen_at": row.get("last_seen_at"),
            "terminated_at": row.get("terminated_at"),
            "created_at": row.get("created_at"),
            "updated_at": row.get("updated_at"),
        }


def _validate_request_inputs(
    *, gpu: str | None, cpu: float | None, memory: int | None, time_limit: int | None
) -> tuple[str | None, float, int, int]:
    norm_gpu: str | None = None
    if gpu not in (None, ""):
        norm_gpu = str(gpu).upper()
        if norm_gpu not in VALID_GPUS:
            raise ValidationError(
                f"invalid gpu: {gpu}; allowed: {', '.join(sorted(VALID_GPUS))}"
            )
    norm_cpu = float(cpu) if cpu is not None else DEFAULT_CPU
    if norm_cpu <= 0:
        raise ValidationError("cpu must be positive")
    norm_memory = int(memory) if memory is not None else DEFAULT_MEMORY_MB
    if norm_memory < 512:
        raise ValidationError("memory must be at least 512 (MiB)")
    norm_time = int(time_limit) if time_limit is not None else DEFAULT_TIME_LIMIT_SECONDS
    if norm_time < MIN_TIME_LIMIT_SECONDS or norm_time > MAX_TIME_LIMIT_SECONDS:
        raise ValidationError(
            f"time_limit must be between {MIN_TIME_LIMIT_SECONDS} and {MAX_TIME_LIMIT_SECONDS} seconds"
        )
    return norm_gpu, norm_cpu, norm_memory, norm_time


def _iso_after(*, seconds: int) -> str:
    return (
        (datetime.now(UTC) + timedelta(seconds=seconds))
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def _parse_iso(value: Any) -> datetime | None:
    if not value:
        return None
    try:
        dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except (TypeError, ValueError):
        return None
    return dt if dt.tzinfo is not None else dt.replace(tzinfo=UTC)


def _env_float(name: str, override: float | None, default: float) -> float:
    if override is not None:
        return float(override)
    raw = os.environ.get(name)
    if raw:
        try:
            return float(raw)
        except ValueError:
            pass
    return default
